name: Terraform OIDC Test

on:
  workflow_dispatch: {}

permissions:
  id-token: write   # Required for GitHub OIDC
  contents: read

jobs:
  oidc-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1   # change if you use another region

      - name: Verify identity
        run: aws sts get-caller-identity
