name: Terraform Apply (IAM Users & Groups)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

permissions:
  id-token: write     # required for OIDC
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: prod   # protect with required reviewers for safety

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}   # set this secret in GitHub
          aws-region: us-east-1                               # change if needed

      - name: Init
        working-directory: terraform
        run: terraform init

      - name: Validate
        working-directory: terraform
        run: terraform validate

      - name: Plan
        id: plan
        working-directory: terraform
        run: terraform plan -input=false -out=tfplan

      - name: Upload plan artifact (PR only)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

      - name: Apply (push to main or manual dispatch)
        if: github.event_name != 'pull_request'
        working-directory: terraform
        run: terraform apply -input=false -auto-approve tfplan || terraform apply -input=false -auto-approve
