name: Terraform Apply (IAM Users & Groups)

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  id-token: write   # needed for OIDC to AWS
  contents: read

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      # ---- All events: init/validate ----
      - name: Init
        working-directory: terraform
        run: terraform init

      - name: Validate
        working-directory: terraform
        run: terraform validate

      # ---- PRs: Plan only ----
      - name: Plan
        if: github.event_name == 'pull_request'
        id: plan
        working-directory: terraform
        run: terraform plan -input=false -out=tfplan

      - name: Upload plan artifact (PR only)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

      # ---- Push to main / manual dispatch: Apply ----
      - name: Apply (push to main or manual dispatch)
        if: github.event_name != 'pull_request'
        working-directory: terraform
        run: terraform apply -input=false -auto-approve
